### ISSUE TITLE
Next pub.dev release?

### ISSUE THREAD

**Issue by TheRedSpy15** [M97Chahboun/github_snitch#33]
Hello. I'd really like to include this in my project but the dependencies in the current version (specifically http) is way too out of date

It has been updated here on github, but I'm not familiar enough for flutter pub to use the updated code without an official release

**Comment by M97Chahboun** [comment]
Today i will update it
And you can search about use package from github...

**Comment by M97Chahboun** [comment]
https://pub.dev/packages/github_snitch
